apiVersion: v1
kind: Service
metadata:
  name: generic-service
spec:
  ports:
    - port: 80
  selector:
    app: generic-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generic-deployment
spec:
  selector:
    matchLabels:
      app: generic-app
  template:
    metadata:
      name: alpine
      labels:
        app: generic-app
    spec:
      containers:
        - name: alpine
          image: alpine:latest
          stdin: True
          tty: True
          ports: 
            - containerPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: generic-app-autoscaler
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: generic-deployment
  targetCPUUtilizationPercentage: 50