# role and role binding used for granting cluster permissions to gcloud user & srv
---
apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-only-role
  namespace: development
rules:
  - apiGroups: ['']
    resources: ['pods', 'services', 'deployments']
    verbs: ['get', 'list', 'watch']
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-only-role-binding
  namespace: development
subjects:
# service account created from createServiceAccount.sh
- kind: User
  # project_id parameterized for git
  name: kubernetes-read-only@%PROJECT_ID%.iam.gserviceaccount.com
roleRef:
  kind: Role
  name: read-only-role
  apiGroup: rbac.authorization.k8s.io
