apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-only-role
  namespace: development
rules:
  - apiGroups: ['']
    resources: ['pods', 'services', 'deployments']
    verbs: ['get', 'list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-only-role-binding
  namespace: development
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: read-only-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: test-organization
    apiGroup: rbac.authorization.k8s.io
