# service accounts are used within kubernetes to authenticate pods to the apiserver
---
# outside of example purposes, secrets would be stored in secret management software
# and retrieved/set in a secure manner as part of a deployment pipeline
apiVersion: v1
kind: Secret
data:
  password: password
metadata:
  name: generic-secret
---
# use the following to create a docker registry secret for authenticating to private registry
# kubectl create secret docker-registry <name> --docker-server=DOCKER_REGISTRY_SERVER --docker-username=DOCKER_USER --docker-password=DOCKER_PASSWORD --docker-email=DOCKER_EMAIL
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: generic-sa
# docker-registry secret created from above kubectl command
imagePullsecrets: 
  - name: docker-registry
secrets:
  - name: generic-secret